<!DOCTYPE html><html lang="zh-CN"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width"><meta name="theme-color" content="#222"><meta name="generator" content="Hexo 5.4.2"><link rel="apple-touch-icon" sizes="180x180" href="/assets/apple-touch-icon.png"><link rel="icon" type="image/png" sizes="32x32" href="/assets/favicon-32x32.png"><link rel="icon" type="image/png" sizes="16x16" href="/assets/favicon-16x16.png"><link rel="mask-icon" href="/assets/safari-pinned-tab.svg" color="#222"><link rel="stylesheet" href="/css/main.css"><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha256-HtsXJanqjKTc8vVQjO4YMhiqFoXkfBsjBWcX91T1jr8=" crossorigin="anonymous"><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.1.1/animate.min.css" integrity="sha256-PR7ttpcvz8qrF57fur/yAx1qXMFJeJFiA6pSzWi0OIE=" crossorigin="anonymous"><script class="next-config" data-name="main" type="application/json">{"hostname":"www.bennyhuo.com","root":"/","images":"/images","scheme":"Pisces","darkmode":false,"version":"8.15.1","exturl":false,"sidebar":{"position":"left","display":"post","padding":18,"offset":12},"copycode":{"enable":true,"style":"default"},"bookmark":{"enable":false,"color":"#222","save":"auto"},"mediumzoom":false,"lazyload":false,"pangu":false,"comments":{"style":"tabs","active":"gittalk","storage":true,"lazyload":false,"nav":null},"stickytabs":false,"motion":{"enable":true,"async":false,"transition":{"menu_item":"fadeInDown","post_block":"fadeIn","post_header":"fadeInDown","post_body":"fadeInDown","coll_header":"fadeInLeft","sidebar":"fadeInUp"}},"prism":false,"i18n":{"placeholder":"搜索...","empty":"没有找到任何搜索结果：${query}","hits_time":"找到 ${hits} 个搜索结果（用时 ${time} 毫秒）","hits":"找到 ${hits} 个搜索结果"}}</script><script src="/js/config.js"></script><meta name="description" content="协程的任务的取消需要靠协程内部调用的协作支持，这就类似于我们线程中断以及对中断状态的响应一样。"><meta property="og:type" content="article"><meta property="og:title" content="破解 Kotlin 协程（5）：协程取消篇"><meta property="og:url" content="https://www.bennyhuo.com/2019/04/30/coroutine-cancellation/index.html"><meta property="og:site_name" content="Benny Huo"><meta property="og:description" content="协程的任务的取消需要靠协程内部调用的协作支持，这就类似于我们线程中断以及对中断状态的响应一样。"><meta property="og:locale" content="zh_CN"><meta property="article:published_time" content="2019-04-30T00:00:00.000Z"><meta property="article:modified_time" content="2024-07-21T13:13:12.813Z"><meta property="article:author" content="Benny Huo"><meta property="article:tag" content="Kotlin Java IntelliJ Android 视频教程"><meta name="twitter:card" content="summary"><link rel="canonical" href="https://www.bennyhuo.com/2019/04/30/coroutine-cancellation/"><script class="next-config" data-name="page" type="application/json">{"sidebar":"","isHome":false,"isPost":true,"lang":"zh-CN","comments":true,"permalink":"https://www.bennyhuo.com/2019/04/30/coroutine-cancellation/","path":"/2019/04/30/coroutine-cancellation/","title":"破解 Kotlin 协程（5）：协程取消篇"}</script><script class="next-config" data-name="calendar" type="application/json">""</script><title>破解 Kotlin 协程（5）：协程取消篇 | Benny Huo</title><script src="/js/third-party/analytics/baidu-analytics.js"></script><script async src="https://hm.baidu.com/hm.js?8158efd7e8cf52cfb7d8420b33755ca8"></script><noscript><link rel="stylesheet" href="/css/noscript.css"></noscript></head><body itemscope itemtype="http://schema.org/WebPage" class="use-motion"><div class="headband"></div><main class="main"><div class="column"><header class="header" itemscope itemtype="http://schema.org/WPHeader"><div class="site-brand-container"><div class="site-nav-toggle"><div class="toggle" aria-label="切换导航栏" role="button"><span class="toggle-line"></span> <span class="toggle-line"></span> <span class="toggle-line"></span></div></div><div class="site-meta"><a href="/" class="brand" rel="start"><i class="logo-line"></i><p class="site-title">Benny Huo</p><i class="logo-line"></i></a><p class="site-subtitle" itemprop="description">学海无涯，其乐无穷</p></div><div class="site-nav-right"><div class="toggle popup-trigger" aria-label="搜索" role="button"></div></div></div><nav class="site-nav"><ul class="main-menu menu"><li class="menu-item menu-item-home"><a href="/" rel="section"><i class="fa fa-house fa-fw"></i>首页</a></li><li class="menu-item menu-item-专栏"><a href="/book/" rel="section"><i class="fa fa-book fa-fw"></i>专栏</a></li><li class="menu-item menu-item-网盘"><a href="https://drive.bennyhuo.com/" rel="section" target="_blank"><i class="fa fa-hard-drive fa-fw"></i>网盘</a></li><li class="menu-item menu-item-项目"><a href="/project/" rel="section"><i class="fa fa-diagram-project fa-fw"></i>项目</a></li><li class="menu-item menu-item-about"><a href="/about/" rel="section"><i class="fa fa-user fa-fw"></i>关于</a></li></ul></nav></header><aside class="sidebar"><div class="sidebar-inner sidebar-nav-active sidebar-toc-active"><ul class="sidebar-nav"><li class="sidebar-nav-toc">文章目录</li><li class="sidebar-nav-overview">站点概览</li></ul><div class="sidebar-panel-container"><div class="post-toc-wrap sidebar-panel"><div class="post-toc animated"><ol class="nav"><li class="nav-item nav-level-2"><a class="nav-link" href="#1-%E7%BA%BF%E7%A8%8B%E7%9A%84%E4%B8%AD%E6%96%AD"><span class="nav-number">1.</span> <span class="nav-text">1. 线程的中断</span></a></li><li class="nav-item nav-level-2"><a class="nav-link" href="#2-%E5%8D%8F%E7%A8%8B%E7%B1%BB%E4%BC%BC%E7%9A%84%E4%BE%8B%E5%AD%90"><span class="nav-number">2.</span> <span class="nav-text">2. 协程类似的例子</span></a></li><li class="nav-item nav-level-2"><a class="nav-link" href="#3-%E5%AE%8C%E5%96%84%E6%88%91%E4%BB%AC%E4%B9%8B%E5%89%8D%E7%9A%84%E4%BE%8B%E5%AD%90"><span class="nav-number">3.</span> <span class="nav-text">3. 完善我们之前的例子</span></a></li><li class="nav-item nav-level-2"><a class="nav-link" href="#4-%E5%86%8D%E8%B0%88-Retrofit-%E7%9A%84%E5%8D%8F%E7%A8%8B%E6%89%A9%E5%B1%95"><span class="nav-number">4.</span> <span class="nav-text">4. 再谈 Retrofit 的协程扩展</span></a><ol class="nav-child"><li class="nav-item nav-level-3"><a class="nav-link" href="#4-1-Jake-Wharton-%E7%9A%84-Adapter-%E5%AD%98%E5%9C%A8%E7%9A%84%E9%97%AE%E9%A2%98"><span class="nav-number">4.1.</span> <span class="nav-text">4.1 Jake Wharton 的 Adapter 存在的问题</span></a></li><li class="nav-item nav-level-3"><a class="nav-link" href="#4-2-%E5%A6%82%E4%BD%95%E6%AD%A3%E7%A1%AE%E7%9A%84%E5%B0%86%E5%9B%9E%E8%B0%83%E8%BD%AC%E6%8D%A2%E4%B8%BA%E5%8D%8F%E7%A8%8B"><span class="nav-number">4.2.</span> <span class="nav-text">4.2 如何正确的将回调转换为协程</span></a></li></ol></li><li class="nav-item nav-level-2"><a class="nav-link" href="#5-%E5%B0%8F%E7%BB%93"><span class="nav-number">5.</span> <span class="nav-text">5. 小结</span></a></li><li class="nav-item nav-level-2"><a class="nav-link" href="#%E5%85%B3%E4%BA%8E%E4%BD%9C%E8%80%85"><span class="nav-number">6.</span> <span class="nav-text">关于作者</span></a></li></ol></div></div><div class="site-overview-wrap sidebar-panel"><div class="site-author animated" itemprop="author" itemscope itemtype="http://schema.org/Person"><img class="site-author-image" itemprop="image" alt="Benny Huo" src="/assets/avatar.jpg"><p class="site-author-name" itemprop="name">Benny Huo</p><div class="site-description" itemprop="description">Google 开发者专家（GDE）<br>《深入理解 Kotlin 协程》作者</div></div><div class="site-state-wrap animated"><nav class="site-state"><div class="site-state-item site-state-posts"><a href="/archives/"><span class="site-state-item-count">91</span> <span class="site-state-item-name">日志</span></a></div><div class="site-state-item site-state-tags"><a href="/tags/"><span class="site-state-item-count">71</span> <span class="site-state-item-name">标签</span></a></div></nav></div><div class="links-of-author animated"><span class="links-of-author-item"><a href="https://github.com/bennyhuo" title="GitHub → https:&#x2F;&#x2F;github.com&#x2F;bennyhuo" rel="noopener me" target="_blank"><i class="fab fa-github fa-fw"></i>GitHub</a> </span><span class="links-of-author-item"><a href="mailto:bennyhuo@kotliner.cn" title="E-Mail → mailto:bennyhuo@kotliner.cn" rel="noopener me" target="_blank"><i class="fa fa-envelope fa-fw"></i>E-Mail</a> </span><span class="links-of-author-item"><a href="https://space.bilibili.com/28615855" title="Bilibli → https:&#x2F;&#x2F;space.bilibili.com&#x2F;28615855" rel="noopener me" target="_blank"><i class="fa fa-play fa-fw"></i>Bilibli</a> </span><span class="links-of-author-item"><a href="https://www.youtube.com/@bennyhuo" title="YouTube → https:&#x2F;&#x2F;www.youtube.com&#x2F;@bennyhuo" rel="noopener me" target="_blank"><i class="fab fa-youtube fa-fw"></i>YouTube</a></span></div></div></div></div></aside></div><div class="main-inner post posts-expand"><div class="post-block"><article itemscope itemtype="http://schema.org/Article" class="post-content" lang="zh-CN"><link itemprop="mainEntityOfPage" href="https://www.bennyhuo.com/2019/04/30/coroutine-cancellation/"><span hidden itemprop="author" itemscope itemtype="http://schema.org/Person"><meta itemprop="image" content="/assets/avatar.jpg"><meta itemprop="name" content="Benny Huo"></span><span hidden itemprop="publisher" itemscope itemtype="http://schema.org/Organization"><meta itemprop="name" content="Benny Huo"><meta itemprop="description" content="Google 开发者专家（GDE）<br>《深入理解 Kotlin 协程》作者"></span><span hidden itemprop="post" itemscope itemtype="http://schema.org/CreativeWork"><meta itemprop="name" content="破解 Kotlin 协程（5）：协程取消篇 | Benny Huo"><meta itemprop="description" content=""></span><header class="post-header"><h1 class="post-title" itemprop="name headline">破解 Kotlin 协程（5）：协程取消篇</h1><div class="post-meta-container"><div class="post-meta"><span class="post-meta-item"><span class="post-meta-item-icon"><i class="far fa-calendar"></i> </span><span class="post-meta-item-text">发表于</span> <time title="创建时间：2019-04-30 00:00:00" itemprop="dateCreated datePublished" datetime="2019-04-30T00:00:00+00:00">2019-04-30</time> </span><span class="post-meta-item"><span class="post-meta-item-icon"><i class="far fa-calendar-check"></i> </span><span class="post-meta-item-text">更新于</span> <time title="修改时间：2024-07-21 13:13:12" itemprop="dateModified" datetime="2024-07-21T13:13:12+00:00">2024-07-21</time> </span><span id="/2019/04/30/coroutine-cancellation/" class="post-meta-item leancloud_visitors" data-flag-title="破解 Kotlin 协程（5）：协程取消篇" title="阅读次数"><span class="post-meta-item-icon"><i class="far fa-eye"></i> </span><span class="post-meta-item-text">阅读次数：</span> <span class="leancloud-visitors-count"></span> </span><span class="post-meta-break"></span> <span class="post-meta-item" title="本文字数"><span class="post-meta-item-icon"><i class="far fa-file-word"></i> </span><span class="post-meta-item-text">本文字数：</span> <span>11k</span> </span><span class="post-meta-item" title="阅读时长"><span class="post-meta-item-icon"><i class="far fa-clock"></i> </span><span class="post-meta-item-text">阅读时长 &asymp;</span> <span>20 分钟</span></span></div></div></header><div class="post-body" itemprop="articleBody"><blockquote><p>协程的任务的取消需要靠协程内部调用的协作支持，这就类似于我们线程中断以及对中断状态的响应一样。</p></blockquote><span id="more"></span><ul><li><a href="https://www.bennyhuo.com/2019/03/31/kotlin-coroutines-00-forword/">破解 Kotlin 协程（0）：前言</a></li><li><a href="https://www.bennyhuo.com/2019/04/01/basic-coroutines/">破解 Kotlin 协程（1）：入门篇</a></li><li><a href="https://www.bennyhuo.com/2019/04/08/coroutines-start-mode/">破解 Kotlin 协程（2）：协程启动篇</a></li><li><a href="https://www.bennyhuo.com/2019/04/11/coroutine-dispatchers/">破解 Kotlin 协程（3）：协程调度篇</a></li><li><a href="https://www.bennyhuo.com/2019/04/23/coroutine-exceptions/">破解 Kotlin 协程（4）：异常处理篇</a></li><li><a href="https://www.bennyhuo.com/2019/04/30/coroutine-cancellation/">破解 Kotlin 协程（5）：协程取消篇</a></li><li><a href="https://www.bennyhuo.com/2019/05/07/coroutine-suspend/">破解 Kotlin 协程（6）：协程挂起篇</a></li><li><a href="https://www.bennyhuo.com/2019/05/26/coroutine-sequence/">破解 Kotlin 协程（7）：序列生成器篇</a></li><li><a href="https://www.bennyhuo.com/2019/05/27/coroutine-android/">破解 Kotlin 协程（8）：Android 篇</a></li><li><a href="https://www.bennyhuo.com/2019/09/16/coroutine-channel/">破解 Kotlin 协程（9）：Channel 篇</a></li><li><a href="https://www.bennyhuo.com/2020/02/03/coroutine-select/">破解 Kotlin 协程（10）：Select 篇</a></li><li><a href="https://www.bennyhuo.com/2020/03/14/coroutine-flow/">破解 Kotlin 协程（11）：Flow 篇</a></li><li><a href="https://www.bennyhuo.com/2019/10/19/coroutine-why-so-called-lightweight-thread/">破解 Kotlin 协程（12）：协程为什么被称为『轻量级线程』？</a></li><li><a href="https://www.bennyhuo.com/2019/12/01/coroutine-implementations/">破解 Kotlin 协程（13）：协程的几类常见的实现</a></li></ul><h2 id="1-线程的中断"><a href="#1-线程的中断" class="headerlink" title="1. 线程的中断"></a>1. 线程的中断</h2><p>我们先从大家熟悉的话题讲起。线程有一个被废弃的 <code>stop</code> 方法，这个方法会让线程立即死掉，并且释放它持有的锁，这样会让它正在读写的存储处于一个不安全的状态，因此 <code>stop</code> 被废弃了。如果我们启动了一个线程并让它执行一些任务，但很快我们就后悔了，<code>stop</code> 还不让用，那该怎么办？</p><figure class="highlight kotlin"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">val</span> thread = thread &#123;</span><br><span class="line">    ...</span><br><span class="line">&#125;</span><br><span class="line">thread.stop() <span class="comment">// !!! Deprecated!!!</span></span><br></pre></td></tr></table></figure><p>我们应该想办法让线程内部正在运行的任务跟我们合作把任务停掉，这样线程内部的任务停止之前还有机会清理一些资源，比如关闭流等等。</p><figure class="highlight kotlin"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">val</span> thread = thread &#123;</span><br><span class="line">    <span class="keyword">try</span> &#123;</span><br><span class="line">        Thread.sleep(<span class="number">10000</span>)</span><br><span class="line">    &#125; <span class="keyword">catch</span> (e: InterruptedException) &#123;</span><br><span class="line">        log(<span class="string">&quot;Interrupted, do cleaning stuff.&quot;</span>)</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br><span class="line">thread.interrupt()</span><br></pre></td></tr></table></figure><p>像 <code>sleep</code> 这样的方法调用，文档明确指出它支持 <code>InterruptedException</code>，因此当线程被标记为中断状态时，它就会抛出 <code>InterruptedException</code> ，那么我们自然就可以捕获异常并做资源清理了。</p><p>所以请注意所谓的协作式的任务终止，协程的取消也就是 <code>cancel</code> 机制的思路也是如此。</p><h2 id="2-协程类似的例子"><a href="#2-协程类似的例子" class="headerlink" title="2. 协程类似的例子"></a>2. 协程类似的例子</h2><p>我们来看一个协程取消的例子：</p><figure class="highlight kotlin"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">fun</span> <span class="title">main</span><span class="params">()</span></span> = runBlocking &#123;</span><br><span class="line">    <span class="keyword">val</span> job1 = launch &#123; <span class="comment">// ①</span></span><br><span class="line">        log(<span class="number">1</span>)</span><br><span class="line">        delay(<span class="number">1000</span>) <span class="comment">// ②</span></span><br><span class="line">        log(<span class="number">2</span>)</span><br><span class="line">    &#125;</span><br><span class="line">    delay(<span class="number">100</span>)</span><br><span class="line">    log(<span class="number">3</span>)</span><br><span class="line">    job1.cancel() <span class="comment">// ③</span></span><br><span class="line">    log(<span class="number">4</span>)</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure><p>这次我们用了一个不一样的写法，我们没有用 suspend main，而是直接用 <code>runBlocking</code> 启动协程，这个方法在 Native 上也存在，都是基于当前线程启动一个类似于 Android 的 Looper 的死循环，或者叫消息队列，可以不断的发送消息给它进行处理。<code>runBlocking</code> 会启动一个 <code>Job</code>，因此这里也存在默认的作用域，不过这对于我们今天的讨论暂时没有太大影响。</p><p>这段代码 ① 处启动了一个子协程，它内部先输出 1，接着开始 <code>delay</code>， <code>delay</code> 与线程的 <code>sleep</code> 不同，它不会阻塞线程，你可以认为它实际上就是触发了一个延时任务，告诉协程调度系统 1000ms 之后再来执行后面的这段代码（也就是 log(2)）；而在这期间，我们在 ③ 处对刚才启动的协程触发了取消，因此在 ② 处的 <code>delay</code> 还没有回调的时候协程就被取消了，因为 <code>delay</code> 可以响应取消，因此 <code>delay</code> 后面的代码就不会再次调度了，不调度的原因也很简单，② 处的 <code>delay</code> 会抛一个 <code>CancellationException</code>：</p><figure class="highlight kotlin"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br></pre></td><td class="code"><pre><span class="line">...</span><br><span class="line">log(<span class="number">1</span>)</span><br><span class="line"><span class="keyword">try</span> &#123;</span><br><span class="line">    delay(<span class="number">1000</span>)</span><br><span class="line">&#125; <span class="keyword">catch</span> (e: Exception) &#123;</span><br><span class="line">    log(<span class="string">&quot;cancelled. <span class="variable">$e</span>&quot;</span>)</span><br><span class="line">&#125;</span><br><span class="line">log(<span class="number">2</span>)</span><br><span class="line">...</span><br></pre></td></tr></table></figure><p>那么输出的结果就不一样了：</p><figure class="highlight plaintext"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br></pre></td><td class="code"><pre><span class="line">06:54:56:361 [main] 1</span><br><span class="line">06:54:56:408 [main] 3</span><br><span class="line">06:54:56:411 [main] 4</span><br><span class="line">06:54:56:413 [main] cancelled. kotlinx.coroutines.JobCancellationException: Job was cancelled; job=StandaloneCoroutine&#123;Cancelling&#125;@e73f9ac</span><br><span class="line">06:54:56:413 [main] 2</span><br></pre></td></tr></table></figure><p>大家看，这与线程的中断逻辑是不是非常的类似呢？</p><h2 id="3-完善我们之前的例子"><a href="#3-完善我们之前的例子" class="headerlink" title="3. 完善我们之前的例子"></a>3. 完善我们之前的例子</h2><p>之前我们有个例子，上一篇文章已经加入了异常处理逻辑，那么这次我们给它加上取消逻辑。之前是这样：</p><figure class="highlight kotlin"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">suspend</span> <span class="function"><span class="keyword">fun</span> <span class="title">getUserCoroutine</span><span class="params">()</span></span> = suspendCoroutine&lt;User&gt; &#123; continuation -&gt;</span><br><span class="line">    getUser(<span class="keyword">object</span> : Callback&lt;User&gt; &#123;</span><br><span class="line">        <span class="keyword">override</span> <span class="function"><span class="keyword">fun</span> <span class="title">onSuccess</span><span class="params">(value: <span class="type">User</span>)</span></span> &#123;</span><br><span class="line">            continuation.resume(value)</span><br><span class="line">        &#125;</span><br><span class="line"></span><br><span class="line">        <span class="keyword">override</span> <span class="function"><span class="keyword">fun</span> <span class="title">onError</span><span class="params">(t: <span class="type">Throwable</span>)</span></span> &#123;</span><br><span class="line">            continuation.resumeWithException(t)</span><br><span class="line">        &#125;</span><br><span class="line">    &#125;)</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure><p>加取消逻辑，那需要我们的 <code>getUser</code> 回调版本支持取消，我们看下我们的 <code>getUser</code> 是怎么实现的：</p><figure class="highlight kotlin"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">fun</span> <span class="title">getUser</span><span class="params">(callback: <span class="type">Callback</span>&lt;<span class="type">User</span>&gt;)</span></span> &#123;</span><br><span class="line">    <span class="keyword">val</span> call = OkHttpClient().newCall(</span><br><span class="line">            Request.Builder()</span><br><span class="line">                    .<span class="keyword">get</span>().url(<span class="string">&quot;https://api.github.com/users/bennyhuo&quot;</span>)</span><br><span class="line">                    .build())</span><br><span class="line"></span><br><span class="line">    call.enqueue(<span class="keyword">object</span> : okhttp3.Callback &#123;</span><br><span class="line">        <span class="keyword">override</span> <span class="function"><span class="keyword">fun</span> <span class="title">onFailure</span><span class="params">(call: <span class="type">Call</span>, e: <span class="type">IOException</span>)</span></span> &#123;</span><br><span class="line">            callback.onError(e)</span><br><span class="line">        &#125;</span><br><span class="line"></span><br><span class="line">        <span class="keyword">override</span> <span class="function"><span class="keyword">fun</span> <span class="title">onResponse</span><span class="params">(call: <span class="type">Call</span>, response: <span class="type">Response</span>)</span></span> &#123;</span><br><span class="line">            response.body()?.let &#123;</span><br><span class="line">                <span class="keyword">try</span> &#123;</span><br><span class="line">                    callback.onSuccess(User.from(it.string()))</span><br><span class="line">                &#125; <span class="keyword">catch</span> (e: Exception) &#123;</span><br><span class="line">                    callback.onError(e) <span class="comment">// 这里可能是解析异常</span></span><br><span class="line">                &#125;</span><br><span class="line">            &#125;?: callback.onError(NullPointerException(<span class="string">&quot;ResponseBody is null.&quot;</span>))</span><br><span class="line">        &#125;</span><br><span class="line">    &#125;)</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure><p>我们发了个网络请求给 Github，让它把一个叫 <code>bennyhuo</code> 的用户信息返回来，我们知道 OkHttp 的这个 <code>Call</code> 是支持 <code>cancel</code> 的， 取消后，网络请求过程中如果读取到这个取消的状态，就会把请求给停止掉。既然这样，我们干脆直接改造 <code>getUser</code> 好了，这样还能省掉我们自己的 <code>Callback</code> 回调过程：</p><figure class="highlight kotlin"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">suspend</span> <span class="function"><span class="keyword">fun</span> <span class="title">getUserCoroutine</span><span class="params">()</span></span> = suspendCancellableCoroutine&lt;User&gt; &#123; continuation -&gt;</span><br><span class="line">    <span class="keyword">val</span> call = OkHttpClient().newCall(...)</span><br><span class="line"></span><br><span class="line">    continuation.invokeOnCancellation &#123; <span class="comment">// ①</span></span><br><span class="line">        log(<span class="string">&quot;invokeOnCancellation: cancel the request.&quot;</span>)</span><br><span class="line">        call.cancel()</span><br><span class="line">    &#125;</span><br><span class="line"></span><br><span class="line">    call.enqueue(<span class="keyword">object</span> : okhttp3.Callback &#123;</span><br><span class="line">        <span class="keyword">override</span> <span class="function"><span class="keyword">fun</span> <span class="title">onFailure</span><span class="params">(call: <span class="type">Call</span>, e: <span class="type">IOException</span>)</span></span> &#123;</span><br><span class="line">            log(<span class="string">&quot;onFailure: <span class="variable">$e</span>&quot;</span>)</span><br><span class="line">            continuation.resumeWithException(e)</span><br><span class="line">        &#125;</span><br><span class="line"></span><br><span class="line">        <span class="keyword">override</span> <span class="function"><span class="keyword">fun</span> <span class="title">onResponse</span><span class="params">(call: <span class="type">Call</span>, response: <span class="type">Response</span>)</span></span> &#123;</span><br><span class="line">            log(<span class="string">&quot;onResponse: <span class="subst">$&#123;response.code()&#125;</span>&quot;</span>)</span><br><span class="line">            response.body()?.let &#123;</span><br><span class="line">                <span class="keyword">try</span> &#123;</span><br><span class="line">                    continuation.resume(User.from(it.string()))</span><br><span class="line">                &#125; <span class="keyword">catch</span> (e: Exception) &#123;</span><br><span class="line">                    continuation.resumeWithException(e)</span><br><span class="line">                &#125;</span><br><span class="line">            &#125; ?: continuation.resumeWithException(NullPointerException(<span class="string">&quot;ResponseBody is null.&quot;</span>))</span><br><span class="line">        &#125;</span><br><span class="line">    &#125;)</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure><p>我们这里用到了 <code>suspendCancellableCoroutine</code>，而不是之前的 <code>suspendCoroutine</code>，这就是为了让我们的挂起函数支持协程的取消。该方法将获取到的 <code>Continuation</code> 包装成了一个 <code>CancellableContinuation</code>，通过调用它的 <code>invokeOnCancellation</code> 方法可以设置一个取消事件的回调，一旦这个回调被调用，那么意味着 <code>getUserCoroutine</code> 调用所在的协程被取消了，这时候我们也要相应的做出取消的响应，也就是把 OkHttp 发出去的请求给取消掉。</p><p>那么我们在调用它的时候，如果遇到了取消，会怎么样呢？</p><figure class="highlight kotlin"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">val</span> job1 = launch &#123; <span class="comment">//①</span></span><br><span class="line">    log(<span class="number">1</span>)</span><br><span class="line">    <span class="keyword">val</span> user = getUserCoroutine()</span><br><span class="line">    log(user)</span><br><span class="line">    log(<span class="number">2</span>)</span><br><span class="line">&#125;</span><br><span class="line">delay(<span class="number">10</span>)</span><br><span class="line">log(<span class="number">3</span>)</span><br><span class="line">job1.cancel()</span><br><span class="line">log(<span class="number">4</span>)</span><br></pre></td></tr></table></figure><p>注意我们启动 ① 之后仅仅延迟了 10ms 就取消了它，网络请求的速度一般来讲还不会这么快，因此取消的时候大概率 <code>getUserCoroutine</code> 被挂起了，因此结果大概率是：</p><figure class="highlight kotlin"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br></pre></td><td class="code"><pre><span class="line"><span class="number">07</span>:<span class="number">31</span>:<span class="number">30</span>:<span class="number">751</span> [main] <span class="number">1</span></span><br><span class="line"><span class="number">07</span>:<span class="number">31</span>:<span class="number">31</span>:<span class="number">120</span> [main] <span class="number">3</span></span><br><span class="line"><span class="number">07</span>:<span class="number">31</span>:<span class="number">31</span>:<span class="number">124</span> [main] invokeOnCancellation: cancel the request.</span><br><span class="line"><span class="number">07</span>:<span class="number">31</span>:<span class="number">31</span>:<span class="number">129</span> [main] <span class="number">4</span></span><br><span class="line"><span class="number">07</span>:<span class="number">31</span>:<span class="number">31</span>:<span class="number">131</span> [OkHttp https:<span class="comment">//api.github.com/...] onFailure: java.io.IOException: Canceled</span></span><br></pre></td></tr></table></figure><p>我们发现，取消的回调被调用了，OkHttp 在收到我们的取消指令之后，也确实停止了网络请求，并且回调给我们一个 IO 异常，这时候我们的协程已经被取消，在处于取消状态的协程上调用 <code>Continuation.resume</code> 、 <code>Continuation.resumeWithException</code> 或者 <code>Continuation.resumeWith</code> 都会被忽略，因此 OkHttp 回调中我们收到 IO 异常后调用的 <code>continuation.resumeWithException(e)</code> 不会有任何副作用。</p><h2 id="4-再谈-Retrofit-的协程扩展"><a href="#4-再谈-Retrofit-的协程扩展" class="headerlink" title="4. 再谈 Retrofit 的协程扩展"></a>4. 再谈 Retrofit 的协程扩展</h2><h3 id="4-1-Jake-Wharton-的-Adapter-存在的问题"><a href="#4-1-Jake-Wharton-的-Adapter-存在的问题" class="headerlink" title="4.1 Jake Wharton 的 Adapter 存在的问题"></a>4.1 Jake Wharton 的 Adapter 存在的问题</h3><p>我在<a href="https://www.bennyhuo.com/2019/04/01/basic-coroutines/">破解 Kotlin 协程 - 入门篇</a> 提到了 Jake Wharton 大神为 Retrofit 写的 协程 Adapter，</p><figure class="highlight gradle"><table><tr><td class="gutter"><pre><span class="line">1</span><br></pre></td><td class="code"><pre><span class="line">implementation <span class="string">&#x27;com.jakewharton.retrofit:retrofit2-kotlin-coroutines-adapter:0.9.2&#x27;</span></span><br></pre></td></tr></table></figure><p>它确实可以完成网络请求，不过有细心的小伙伴发现了它的问题：它怎么取消呢？我们把使用它的代码贴出来：</p><figure class="highlight kotlin"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">interface</span> <span class="title class_">GitHubServiceApi</span> &#123;</span><br><span class="line">    <span class="meta">@GET(<span class="string">&quot;users/&#123;login&#125;&quot;</span>)</span></span><br><span class="line">    <span class="function"><span class="keyword">fun</span> <span class="title">getUserCoroutine</span><span class="params">(<span class="meta">@Path(<span class="string">&quot;login&quot;</span>)</span> login: <span class="type">String</span>)</span></span>: Deferred&lt;User&gt;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure><p>定义好接口，创建 Retrofit 实例的时候传入对应的 Adapter：</p><figure class="highlight kotlin"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">val</span> gitHubServiceApi <span class="keyword">by</span> lazy &#123;</span><br><span class="line">    <span class="keyword">val</span> retrofit = retrofit2.Retrofit.Builder()</span><br><span class="line">            .baseUrl(<span class="string">&quot;https://api.github.com&quot;</span>)</span><br><span class="line">            .addConverterFactory(GsonConverterFactory.create())</span><br><span class="line">            .addCallAdapterFactory(CoroutineCallAdapterFactory()) <span class="comment">// 这里添加 Adapter</span></span><br><span class="line">            .build()</span><br><span class="line"></span><br><span class="line">    retrofit.create(GitHubServiceApi::<span class="keyword">class</span>.java)</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure><p>用的时候就这样：</p><figure class="highlight kotlin"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">val</span> deferred = gitHubServiceApi.getUserCoroutine(<span class="string">&quot;bennyhuo&quot;</span>)</span><br><span class="line"><span class="keyword">try</span> &#123;</span><br><span class="line">    showUser(deferred.await())</span><br><span class="line">&#125; <span class="keyword">catch</span> (e: Exception) &#123;</span><br><span class="line">    showError(e)</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure><p>如果要取消，我们可以直接调用 <code>deferred.cancel()</code>，例如：</p><figure class="highlight kotlin"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br></pre></td><td class="code"><pre><span class="line">log(<span class="string">&quot;1&quot;</span>)</span><br><span class="line"><span class="keyword">val</span> deferred = gitHubServiceApi.getUserCoroutine(<span class="string">&quot;bennyhuo&quot;</span>)</span><br><span class="line">log(<span class="string">&quot;2&quot;</span>)</span><br><span class="line">withContext(Dispatchers.IO)&#123;</span><br><span class="line">    deferred.cancel()</span><br><span class="line">&#125;</span><br><span class="line"><span class="keyword">try</span> &#123;</span><br><span class="line">    showUser(deferred.await())</span><br><span class="line">&#125; <span class="keyword">catch</span> (e: Exception) &#123;</span><br><span class="line">    showError(e)</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure><p>运行结果如下：</p><figure class="highlight plaintext"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br></pre></td><td class="code"><pre><span class="line">12:59:54:185 [DefaultDispatcher-worker-1] 1</span><br><span class="line">12:59:54:587 [DefaultDispatcher-worker-1] 2</span><br><span class="line">kotlinx.coroutines.JobCancellationException: Job was cancelled; job=CompletableDeferredImpl&#123;Cancelled&#125;@36699211</span><br></pre></td></tr></table></figure><p>这种情况下，其实网络请求确实是被取消的，这一点我们可以看下源码的处理：</p><figure class="highlight kotlin"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br></pre></td><td class="code"><pre><span class="line">...</span><br><span class="line"><span class="keyword">override</span> <span class="function"><span class="keyword">fun</span> <span class="title">adapt</span><span class="params">(call: <span class="type">Call</span>&lt;<span class="type">T</span>&gt;)</span></span>: Deferred&lt;T&gt; &#123;</span><br><span class="line">      <span class="keyword">val</span> deferred = CompletableDeferred&lt;T&gt;()</span><br><span class="line"></span><br><span class="line">      deferred.invokeOnCompletion &#123; <span class="comment">// ①</span></span><br><span class="line">        <span class="keyword">if</span> (deferred.isCancelled) &#123;</span><br><span class="line">          call.cancel()</span><br><span class="line">        &#125;</span><br><span class="line">      &#125;</span><br><span class="line"></span><br><span class="line">      call.enqueue(<span class="keyword">object</span> : Callback&lt;T&gt; &#123;</span><br><span class="line">        ...</span><br><span class="line">      &#125;     </span><br><span class="line">&#125;</span><br><span class="line">...</span><br></pre></td></tr></table></figure><p>注意 ① 处，<code>invokeOnCompletion</code> 在协程进入完成状态时触发，包括异常和正常完成，那么在这时候如果发现它的状态是已经取消的，那么结果就直接调用 <code>Call</code> 的取消即可。</p><p>这看上去确实很正常啊~ 不过 @阿永 在公众号的评论里面提到了一个 Case，仔细一看还真是有问题。我们给出示例来复现这个 Case：</p><figure class="highlight kotlin"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">val</span> job = GlobalScope.launch &#123;</span><br><span class="line">    log(<span class="string">&quot;1&quot;</span>)</span><br><span class="line">    <span class="keyword">val</span> deferred = gitHubServiceApi.getUserCoroutine(<span class="string">&quot;bennyhuo&quot;</span>)</span><br><span class="line">    log(<span class="string">&quot;2&quot;</span>)</span><br><span class="line">    deferred.invokeOnCompletion &#123;</span><br><span class="line">        log(<span class="string">&quot;invokeOnCompletion, <span class="variable">$it</span>, <span class="subst">$&#123;deferred.isCancelled&#125;</span>&quot;</span>)</span><br><span class="line">    &#125;</span><br><span class="line">    <span class="keyword">try</span> &#123;</span><br><span class="line">        showUser(deferred.await())</span><br><span class="line">    &#125; <span class="keyword">catch</span> (e: Exception) &#123;</span><br><span class="line">        showError(e)</span><br><span class="line">    &#125;</span><br><span class="line">    log(<span class="number">3</span>)</span><br><span class="line">&#125;</span><br><span class="line">delay(<span class="number">10</span>)</span><br><span class="line">job.cancelAndJoin()</span><br></pre></td></tr></table></figure><p>我们启动一个协程，在其中执行网络请求，那么正常来说，这时候 <code>getUserCoroutine</code> 返回的 <code>Deferred</code> 可以当做一个子协程，它应当遵循默认的作用域规则，在父作用域取消时被取消掉，但现实却并不是这样：</p><figure class="highlight kotlin"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br></pre></td><td class="code"><pre><span class="line"><span class="number">13</span>:<span class="number">06</span>:<span class="number">54</span>:<span class="number">332</span> [DefaultDispatcher-worker-<span class="number">1</span>] <span class="number">1</span></span><br><span class="line"><span class="number">13</span>:<span class="number">06</span>:<span class="number">54</span>:<span class="number">829</span> [DefaultDispatcher-worker-<span class="number">1</span>] <span class="number">2</span></span><br><span class="line">kotlinx.coroutines.JobCancellationException: Job was cancelled; job=StandaloneCoroutine&#123;Cancelling&#125;@19aea38c</span><br><span class="line"><span class="number">13</span>:<span class="number">06</span>:<span class="number">54</span>:<span class="number">846</span> [DefaultDispatcher-worker-<span class="number">1</span>] <span class="number">3</span></span><br><span class="line"><span class="number">13</span>:<span class="number">06</span>:<span class="number">56</span>:<span class="number">937</span> [OkHttp https:<span class="comment">//api.github.com/...] invokeOnCompletion, null, false</span></span><br></pre></td></tr></table></figure><p>我们看到在调用 <code>deferred.await()</code> 的时候抛了个取消异常，这主要是因为 <code>await()</code> 所在的协程已经被我们用 <code>cancelAndJoin()</code> 取消，但从随后 <code>invokeOnCompletion</code> 的回调结果来看， <code>getUserCoroutine</code> 返回的 <code>Deferred</code> 并没有被取消，再仔细一看，时间上这个回调比前面的操作晚了 2s，那必然是网络请求返回之后才回调的。</p><p>所以问题究竟在哪里？在 <code>CoroutineCallAdapterFactory</code> 的实现中，为了实现异步转换，手动创建了一个 <code>CompletableDeferred</code>：</p><figure class="highlight kotlin"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">override</span> <span class="function"><span class="keyword">fun</span> <span class="title">adapt</span><span class="params">(call: <span class="type">Call</span>&lt;<span class="type">T</span>&gt;)</span></span>: Deferred&lt;T&gt; &#123;</span><br><span class="line">  <span class="keyword">val</span> deferred = CompletableDeferred&lt;T&gt;() <span class="comment">// ①</span></span><br><span class="line">  ...</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure><p>这个 <code>CompletableDeferred</code> 本身就是一个 <code>Job</code> 的实现，它的构造可接受一个 <code>Job</code> 实例作为它的父协程，那么问题来了，这里并没有告诉它父协程究竟是谁，因此也就谈不上作用域的事儿了，这好像我们用 <code>GlobalScope.launch</code> 启动了一个协程一样。如果大家在 Android 当中使用 <code>MainScope</code>，那么同样因为前面说到的这个原因，导致 <code>CompletableDeferred</code> 没有办法被取消。</p><blockquote><p>@阿永 在公众号评论中提到这个问题，并提到了一个比较好的解决方案，下面我们为大家详细介绍。感谢 @阿永。</p></blockquote><p>说到这里我们再简单回顾下，作用域主要有 <code>GlobalScope</code>、<code>coroutineScope</code>、<code>supervisorScope</code>，对于取消，除了 <code>supervisorScope</code> 比较特别是单向取消，即父协程取消后子协程都取消，Android 中 <code>MainScope</code> 就是一个调度到 UI 线程的 <code>supervisorScope</code>；<code>coroutineScope</code> 的逻辑则是父子相互取消的逻辑；而 <code>GlobalScope</code> 会启动一个全新的作用域，与它外部隔离，内部遵循默认的协程作用域规则。</p><p>那么有没有办法解决这个问题呢？</p><p>直接解决还是比较困难的，因为 <code>CompletableDeferred</code> 构造所处的调用环境不是 suspend 函数，因而也没有办法拿到（很可能根本就没有！）父协程。</p><h3 id="4-2-如何正确的将回调转换为协程"><a href="#4-2-如何正确的将回调转换为协程" class="headerlink" title="4.2 如何正确的将回调转换为协程"></a>4.2 如何正确的将回调转换为协程</h3><p>前面我们提到既然 <code>adapt</code> 方法不是 suspend 方法，那么我们是不是应该在其他位置创建协程呢？</p><p>其实我们前面在讲 <code>getUserCoroutine</code> 的时候就不断为大家展示了如何将一个回调转换为协程调用的方法：</p><figure class="highlight kotlin"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">suspend</span> <span class="function"><span class="keyword">fun</span> <span class="title">getUserCoroutine</span><span class="params">()</span></span> = suspendCancellableCoroutine&lt;User&gt; &#123; continuation -&gt;</span><br><span class="line">    ...</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure><p><code>suspendCancellableCoroutine</code> 跟最初我们提到的 <code>suspendCoroutine</code> 一样，都是要获取当前协程的 <code>Continuation</code> 实例，这实际上就相当于要继承当前协程的上下文，因此我们只需要在真正需要切换协程的时候再去做这个转换即可：</p><figure class="highlight kotlin"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">public</span> <span class="keyword">suspend</span> <span class="function"><span class="keyword">fun</span> <span class="type">&lt;T : Any&gt;</span> Call<span class="type">&lt;T&gt;</span>.<span class="title">await</span><span class="params">()</span></span>: T &#123;</span><br><span class="line">    <span class="keyword">return</span> suspendCancellableCoroutine &#123; continuation -&gt;</span><br><span class="line">        enqueue(<span class="keyword">object</span> : Callback&lt;T&gt; &#123;</span><br><span class="line">            <span class="keyword">override</span> <span class="function"><span class="keyword">fun</span> <span class="title">onResponse</span><span class="params">(call: <span class="type">Call</span>&lt;<span class="type">T</span>&gt;?, response: <span class="type">Response</span>&lt;<span class="type">T</span>?&gt;)</span></span> &#123;</span><br><span class="line">                continuation.resumeWith(runCatching &#123; <span class="comment">// ①</span></span><br><span class="line">                    <span class="keyword">if</span> (response.isSuccessful) &#123;</span><br><span class="line">                        response.body()</span><br><span class="line">                            ?: <span class="keyword">throw</span> NullPointerException(<span class="string">&quot;Response body is null: <span class="variable">$response</span>&quot;</span>)</span><br><span class="line">                    &#125; <span class="keyword">else</span> &#123;</span><br><span class="line">                        <span class="keyword">throw</span> HttpException(response)</span><br><span class="line">                    &#125;</span><br><span class="line">                &#125;)</span><br><span class="line">            &#125;</span><br><span class="line"></span><br><span class="line">            <span class="keyword">override</span> <span class="function"><span class="keyword">fun</span> <span class="title">onFailure</span><span class="params">(call: <span class="type">Call</span>&lt;<span class="type">T</span>&gt;, t: <span class="type">Throwable</span>)</span></span> &#123;</span><br><span class="line">                <span class="keyword">if</span> (continuation.isCancelled) <span class="keyword">return</span> <span class="comment">// ②</span></span><br><span class="line">                continuation.resumeWithException(t)</span><br><span class="line">            &#125;</span><br><span class="line">        &#125;)</span><br><span class="line"></span><br><span class="line">        continuation.invokeOnCancellation &#123;</span><br><span class="line">            <span class="keyword">try</span> &#123;</span><br><span class="line">                cancel()</span><br><span class="line">            &#125; <span class="keyword">catch</span> (ex: Throwable) &#123;  <span class="comment">// ③</span></span><br><span class="line">                <span class="comment">//Ignore cancel exception </span></span><br><span class="line">            &#125;</span><br><span class="line">        &#125;</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure><p>大家看着这段代码会不会很眼熟？这与我们 <code>getUserCoroutine</code> 的写法几乎如出一辙，不过有几处细节值得关注，我用数字标注了他们的位置：</p><ul><li>① 处 <code>runCatching</code> 可以将一段代码的运行结果或者抛出的异常封装到一个 <code>Result</code> 类型当中，Kotlin 1.3 开始新增了 <code>Continuation.resumeWith(Result)</code> 这个方法， 这个点比起我们前面的写法更具 Kotlin 风格。</li><li>② 处在异常抛出时，判断了是否已经被取消。实际上如果网络请求被取消，这个回调确实会被调到，那么由于取消的操作是协程的由 <code>Continuation</code> 的取消发起的，因此这时候没必要再调用 <code>continuation.resumeWithException(t)</code> 来将异常再抛回来了。尽管我们前面其实也提到过，这时候继续调用 <code>continuation.resumeWithException(t)</code> 也没有任何逻辑上的副作用，但性能上多少还是会有一些开销。</li><li>③ 处，尽管 <code>Call.cancel</code> 的调用比较安全，但网络环境和状态难免情况复杂，因此对异常进行捕获会让这段代码更加健壮。如果 <code>cancel</code> 抛异常而没有捕获的话，那么等同于协程体内部抛出异常，具体如何传播看所在作用域的相关定义了。</li></ul><p>需要指出的是，这段代码片段源自 <a target="_blank" rel="noopener" href="https://github.com/gildor/kotlin-coroutines-retrofit">gildor/kotlin-coroutines-retrofit</a> ，大家也可以直接添加依赖进行使用：</p><figure class="highlight gradle"><table><tr><td class="gutter"><pre><span class="line">1</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">compile</span> <span class="string">&#x27;ru.gildor.coroutines:kotlin-coroutines-retrofit:1.1.0&#x27;</span></span><br></pre></td></tr></table></figure><p>这个框架代码量很少，但经过各路 Kotlin 协程专家的锤炼，逻辑手法很细腻，值得大家学习。</p><h2 id="5-小结"><a href="#5-小结" class="headerlink" title="5. 小结"></a>5. 小结</h2><p>这篇文章我们从线程中断的概念切入，类比学习协程的取消，实际上大家就会发现这二者从逻辑上和场景上有多么的相似。接着我们将之前我们一直提到的回调转协程的例子进一步升级，支持取消，这样大家就可以轻易的将回调转变为协程的挂起调用了。最后我们还分析了一下 Retrofit 的协程扩展的一些问题和解决方法，这个例子也进一步可以引发我们对协程作用域以及如何将现有程序协程化的思考。</p><p>再稍微提一句，协程不是一个简单的东西，毕竟它的原理涉及到对操作系统调度、程序运行机制这样程序界毕竟原始的话题，但你说如果我对前面提到的这些都不是很熟悉或者根本没有接触过，是不是就要跟协程拜拜了呢，其实也不是，只不过如果你对这些都不熟悉，那么可能需要多加练习培养出感觉，而不必一开始就关注原理和细节，依样画葫芦一样可以用的很好，就像大家不知道 RxJava 原理一样可以用的很好一样，协程也可以做到这一点的。</p><p>当然，作为一个有追求的程序员，我们不止要会用，还要用得好，无论如何我们都需要知道来龙去脉，这其中涉及到的基础知识的欠缺也是需要尽快补充的，不能偷懒哈 ：）</p><hr><h2 id="关于作者"><a href="#关于作者" class="headerlink" title="关于作者"></a>关于作者</h2><p><strong>霍丙乾 bennyhuo</strong>，Google 开发者专家（Kotlin 方向）；<strong>《深入理解 Kotlin 协程》</strong> 作者（机械工业出版社，2020.6）；<strong>《深入实践 Kotlin 元编程》</strong> 作者（机械工业出版社，2023.8）；移动客户端工程师，先后就职于腾讯地图、猿辅导、腾讯视频。</p><ul><li>GitHub：<a target="_blank" rel="noopener" href="https://github.com/bennyhuo">https://github.com/bennyhuo</a></li><li>博客：<a href="https://www.bennyhuo.com/">https://www.bennyhuo.com</a></li><li>bilibili：<a target="_blank" rel="noopener" href="https://space.bilibili.com/28615855"><strong>霍丙乾 bennyhuo</strong></a></li><li>微信公众号：<strong>霍丙乾 bennyhuo</strong></li></ul></div><footer class="post-footer"><div class="post-nav"><div class="post-nav-item"><a href="/2019/04/23/coroutine-exceptions/" rel="prev" title="破解 Kotlin 协程（4）：异常处理篇"><i class="fa fa-chevron-left"></i> 破解 Kotlin 协程（4）：异常处理篇</a></div><div class="post-nav-item"><a href="/2019/05/07/coroutine-suspend/" rel="next" title="破解 Kotlin 协程（6）：协程挂起篇">破解 Kotlin 协程（6）：协程挂起篇 <i class="fa fa-chevron-right"></i></a></div></div></footer></article></div><div class="comments gitalk-container"></div></div></main><footer class="footer"><div class="footer-inner"><div class="copyright">&copy; 2018 – <span itemprop="copyrightYear">2024</span> <span class="with-love"><i class="fa fa-heart"></i> </span><span class="author" itemprop="copyrightHolder">Benny Huo</span></div><div class="wordcount"><span class="post-meta-item"><span class="post-meta-item-icon"><i class="fa fa-chart-line"></i> </span><span title="站点总字数">497k</span> </span><span class="post-meta-item"><span class="post-meta-item-icon"><i class="fa fa-coffee"></i> </span><span title="站点阅读时长">15:04</span></span></div><div class="powered-by">由 <a href="https://hexo.io/" rel="noopener" target="_blank">Hexo</a> & <a href="https://theme-next.js.org/pisces/" rel="noopener" target="_blank">NexT.Pisces</a> 强力驱动</div></div></footer><div class="back-to-top" role="button" aria-label="返回顶部"><i class="fa fa-arrow-up fa-lg"></i> <span>0%</span></div><noscript><div class="noscript-warning">Theme NexT works best with JavaScript enabled</div></noscript><script src="https://cdnjs.cloudflare.com/ajax/libs/animejs/3.2.1/anime.min.js" integrity="sha256-XL2inqUJaslATFnHdJOi9GfQ60on8Wx1C2H8DYiN1xY=" crossorigin="anonymous"></script><script src="/js/comments.js"></script><script src="/js/utils.js"></script><script src="/js/motion.js"></script><script src="/js/next-boot.js"></script><script class="next-config" data-name="leancloud_visitors" type="application/json">{"enable":true,"app_id":"FicBFjnnYPST748WV6dmgumh-gzGzoHsz","app_key":"9GE81hTRn176FdLAdUrJBWON","server_url":null,"security":false}</script><script src="/js/third-party/statistics/lean-analytics.js"></script><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/gitalk/1.8.0/gitalk.css" integrity="sha256-AJnUHL7dBv6PGaeyPQJcgQPDjt/Hn/PvYZde1iqfp8U=" crossorigin="anonymous"><script class="next-config" data-name="gitalk" type="application/json">{"enable":true,"github_id":"bennyhuo","repo":"Bennyhuo","client_id":"7d2353275afc8d2a5ba3","client_secret":"b43a5cabf6064d62cd3fea35adde9609ca49887f","admin_user":"bennyhuo","distraction_free_mode":true,"proxy":"https://silent-lake-5dba.bennyhuo.workers.dev/?https://github.com/login/oauth/access_token","language":"zh-CN","owner":"bennyhuo","js":{"url":"https://cdnjs.cloudflare.com/ajax/libs/gitalk/1.8.0/gitalk.min.js","integrity":"sha256-MVK9MGD/XJaGyIghSVrONSnoXoGh3IFxLw0zfvzpxR4="},"path_md5":"b236527ae90a4e6480684b2ab88f9132"}</script><script src="/js/third-party/comments/gitalk.js"></script></body></html>